const faker = require('faker');
export default data = [
  {
    image: faker.random.image(),
    avatar: 'https://picsum.photos/id/1005/400',
    desc: faker.commerce.productDescription(),
    name: faker.commerce.product(),
    price: faker.commerce.price(),
    rating: 3,
    key: '1',
    phoneNumber: faker.phone.phoneNumber().toString(),
    sellerName: faker.name.findName().toString(),
  },
  {
    image: faker.random.image(),
    avatar: 'https://picsum.photos/id/0/400',
    desc: faker.commerce.productDescription().toString(),
    name: faker.commerce.product(),
    price: faker.commerce.price(),
    rating: 5,
    key: '2',
    phoneNumber: faker.phone.phoneNumber(),
    sellerName: faker.name.findName(),
  },
  {
    image: faker.random.image(),
    avatar: 'https://picsum.photos/id/0/400',
    desc: faker.commerce.productDescription().toString(),
    name: faker.commerce.product(),
    price: faker.commerce.price(),
    rating: 5,
    key: '3',
    phoneNumber: faker.phone.phoneNumber(),
    sellerName: faker.name.findName(),
  },
  // {
  //   image: 'https://picsum.photos/id/205/400',
  //   avatar: 'https://picsum.photos/id/0/400',
  //   desc: faker.commerce.productDescription().toString(),
  //   name: faker.commerce.product(),
  //   price: faker.commerce.price(),
  //   rating: 5,
  //   key: '3',
  //   phoneNumber: faker.phone.phoneNumber(),
  //   sellerName: faker.name.findName(),
  // },
  // {
  //   image: 'https://picsum.photos/id/320/400',
  //   avatar: 'https://picsum.photos/id/0/400',
  //   desc: faker.commerce.productDescription().toString(),
  //   name: faker.commerce.product(),
  //   price: 5600,
  //   rating: 5,
  //   key: '4',
  //   phoneNumber: faker.phone.phoneNumber(),
  //   sellerName: faker.name.findName(),
  // },
];
